on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}@${{ secrets.HOST }} "ls"
    - name: cleanup
      run: rm -rf ~/.ssh
